package com.sporekart.notification.domain;

public enum NotificationEventType {
    // Product Commerce Events
    ORDER_CONFIRMED,
    ORDER_CANCELLED,
    ORDER_PACKED,
    SHIPMENT_HANDOVER,
    SHIPMENT_SHIPPED,
    SHIPMENT_IN_TRANSIT,
    SHIPMENT_OUT_FOR_DELIVERY,
    ORDER_DELIVERED,
    
    // Refunds
    REFUND_INITIATED,
    REFUND_PROCESSING,
    REFUND_COMPLETED,
    REFUND_FAILED,

    // Training Commerce
    ENROLLMENT_CONFIRMED,
    ENROLLMENT_CANCELLED,

    // Wallet Financial Events
    WALLET_TOPUP_SUCCESS,
    WALLET_REFUND_CREDIT,
    WALLET_PAYMENT_SUCCESS,
    WALLET_WITHDRAWAL_REQUESTED,
    WALLET_WITHDRAWAL_PROCESSING,
    WALLET_WITHDRAWAL_COMPLETED,
    WALLET_WITHDRAWAL_FAILED,
    WALLET_WITHDRAWAL_REVERSED,

    // Abandoned Commerce
    CART_ABANDONED,
    ENROLLMENT_CHECKOUT_ABANDONED,

    // Support Ticket Events
    SUPPORT_TICKET_CLOSED
}
