spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://${SUPABASE_DB_HOST:aws-0-ap-northeast-1.pooler.supabase.com}:${SUPABASE_DB_PORT:6543}/${SUPABASE_DB_NAME:postgres}?sslmode=require&prepareThreshold=0}
    driver-class-name: ${SPRING_DATASOURCE_DRIVER:org.postgresql.Driver}
    username: ${SPRING_DATASOURCE_USERNAME:${SUPABASE_DB_USERNAME:postgres.irwiiyowpppdynbmwwuz}}
    password: ${SPRING_DATASOURCE_PASSWORD:${SUPABASE_DB_PASSWORD:MyDbSporekart@123#}}
  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
    properties:
      hibernate:
        dialect: ${HIBERNATE_DIALECT:org.hibernate.dialect.PostgreSQLDialect}
    show-sql: false
  flyway:
    enabled: ${SPRING_FLYWAY_ENABLED:true}
    baseline-on-migrate: true
    locations: classpath:db/migration

logging:
  level:
    com.sporekart: DEBUG
    org.springframework.security: DEBUG
