spring:
  jpa:
    show-sql: false

server:
  error:
    include-stacktrace: never
    include-message: never

logging:
  level:
    root: INFO
    com.sporekart: INFO

sporekart:
  mail:
    use-real-smtp: ${USE_REAL_SMTP:true}
  twilio:
    use-real-twilio: ${USE_REAL_TWILIO_SMS:true}

